### ISSUE TITLE
The requested resource /2010-04-01/ ... was not found

### ISSUE THREAD

**Issue by ghost** [RobSpectre/Call-Your-Family#3]
After setting the ENV variables for my Twilio Auth / App / Number ids, I ran `python configure.py` but got the error: 

```
The requested resource /2010-04-01/Accounts/<MY ID>/Applications/<MY ID>.json was not found
```

`<MY ID>` was not literally part of the error but I'm replacing my credentials. 

I don't write much Python.

**Comment by ghost** [comment]
Hi, I noticed there was an update on this project so I gave it another try. 
This time I got a different error when running `configure.py` with the API KEYS.:

``` txt
Configuring your Twilio hackpack...
Could not find Heroku remote in your .git config.  Have you created the Heroku app?
Traceback (most recent call last):
  File "configure.py", line 372, in <module>
    main()
  File "configure.py", line 369, in main
    configure.start()
  File "configure.py", line 68, in start
    self.host = self.getHerokuHostname()
  File "configure.py", line 283, in getHerokuHostname
    raise ConfigurationError("Could not find Heroku remote in " \
__main__.ConfigurationError
txt
```
